<div>
    <p style="text-align:justify"><img alt="" src="https://1.bp.blogspot.com/-91Ny-XLNxOE/X0OQ8FmGNuI/AAAAAAAAAWA/ozTFQrV7vHMX0VD6W-PXbEKVbZ_EHnUSwCLcBGAsYHQ/s3157/Untitled-1.jpg" style="height:100%; width:100%"></p>
    <div class="container">
<h1 >Penghargaan</h1>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">PENGHARGAAN YANG DIRAIH SMK WIKRAMA DARI TAHUN KE TAHUN :</span></strong></span></p>
<ul>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">2 Mei 2018</span></strong><span style="font-size:11.0pt">, SMK Wikrama menerima penghargaan anugerah pendidikan kategori Sekolah Inspiratif dalam rangka Peringatan Hari Pendidikan Nasional Tingkat Kota Bogor tahun 2018</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">2017</span></strong><span style="font-size:11.0pt">,</span> <span style="font-size:11.0pt">SMK Wikrama Bogor menjadi tuan rumah dalam acara peringatan Hari BUMI Internasional yang dihadiri oleh Prof. Rachmat Witoelar (Utusan Khusus Presiden untuk Pengendalian Perubahan Iklim) dan Walikota Bogor</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">2016</span></strong><span style="font-size:11.0pt">, Penghargaan <em>Indonesia Green Award</em></span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juni 2014</span></strong><span style="font-size:11.0pt">, Kepala SMK Wikrama Bogor menerima penghargaan Green Award kategori Green School dari Menteri Kehutanan RI</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juli 2013</span></strong><span style="font-size:11.0pt">, Kepala SMK Wikrama Bogor menerima penghargaan Green Award kategori Green School dari Menteri Kehutanan RI</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juli 2013</span></strong><span style="font-size:11.0pt">, SMK Wikrama Bogor menerima penghargaan&nbsp; dari Walikota Bogor sebagai Sekolah Adiwiyata</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juli 2013</span></strong><span style="font-size:11.0pt">, Kepala SMK Wikrama Bogor menerima penghargaan Green Award kategori Green School dari Menteri Kehutanan RI</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">November 2013</span></strong><span style="font-size:11.0pt">, Kepala SMK Wikrama Bogor memperoleh penghargaan Kepala Sekolah Berprestasi di bidang lingkungan dan mengikuti training lesson study ke Tokyo Jepang</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juni 2012</span></strong><span style="font-size:11.0pt">, SMK Wikrama Bogor menerima penghargaan Sekolah Adiwiyata Mandiri dari Menteri Pendidikan dan Kebudayaan RI dan Menteri Negara Lingkungan Hidup RI</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">September 2012</span></strong><span style="font-size:11.0pt">, SMK Wikrama Bogor memperoleh penghargaan Indonesia Green Awards</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Selama tahun 2013</span></strong><span style="font-size:11.0pt">, SMK Wikrama Bogor mendapatkan Penghargaan Sebagai Sekolah Adiwiyata Tahun Kedua. Selain itu, SMK Wikrama Bogor menerima penghargaan sebagai Sekolah Peduli dan Berbudaya Lingkungan Tingkat Nasional.</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juni 2010</span></strong><span style="font-size:11.0pt">, SMK Wikrama Bogor menerima penghargaan dari Menteri Negara Lingkungan Hidup dan Menteri Pendidikan Nasional sebagai Sekolah Adiwiyata</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Juni 2009</span></strong><span style="font-size:11.0pt">, Mendapat penghargaan dari Menteri Negara Lingkungan Hidup dan Menteri Pendidikan Nasional&nbsp; sebagai Calon Sekolah Adiwiyata 2009</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">9 Februari 2009</span></strong><span style="font-size:11.0pt">, SMK Wikrama terpilih menjadi calon peserta penghargaan Sekolah Adiwiyata Tingkat Propinsi Jawa Barat</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Agustus 2008</span></strong><span style="font-size:11.0pt">, Mendapat penghargaan dari Gubernur Propinsi Jawa Barat sebagai Sekolah Berbudaya Lingkungan Tingkat Propinsi Katagori SMK bidang Kehalian Non-Teknologi</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">November 2007</span></strong><span style="font-size:11.0pt">, Mendapat piagam penghargaan dari Wali Kota Bogor sebagai Sekolah Terbaik Lomba Usaha Kesehatan Sekolah Tingkat SLTA Tahun 2007 Tingkat Kota Bogor</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">3 Juni 2007</span></strong><span style="font-size:11.0pt">, Mendapat piagam penghargaan dari Walikota Bogor, sebagai sekolah Pelaksana Penerapan Kawasan Tanpa Rokok tingkat Sekolah tahun 2007</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">November 2007</span></strong><span style="font-size:11.0pt">, Mendapat piagam penghargaan dari Wali Kota Bogor sebagai Sekolah Terbaik Lomba Usaha Kesehatan Sekolah Tingkat SLTA Tahun 2007 Tingkat Kota Bogor</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">3 Juni 2007</span></strong><span style="font-size:11.0pt">, Mendapat piagam penghargaan dari Walikota Bogor, sebagai sekolah Pelaksana Penerapan Kawasan Tanpa Rokok tingkat Sekolah tahun 2007</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">2 Mei 2007</span></strong><span style="font-size:11.0pt">, Mendapat piagam penghargaan dari Walikota Bogor dalam Lomba Tata Upacara Bendera Tingkat SLTA/MA dalam rangka Hari Pendidikan Nasional Tahun 2007 Tingkat Kota Bogor</span></span></li>
<li style="text-align:justify"><span style="font-size:12pt"><strong><span style="font-size:11.0pt">Mei 2005</span></strong><span style="font-size:11.0pt">, Diberikan penghargaan sebagai Sekolah Sehat tingkat Berwawasan Wiyata Mandala Tingkat Sekolah Kejuruan tahun 2005 oleh Walikota Bogor</span></span></li>
</ul>
</div>
</div>
